import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Nav from './Components/Nav.jsx';
import SideBar from './Components/SideBar.jsx';
import Footer from './Components/Footer.jsx';
import Map from './Components/Map.jsx';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >

        {children}
   
        <Nav/>
       <main className= " flex items-center">
        <SideBar/>
        <Map/>
       </main>
    <Footer/>

      </body>
    </html>
  );
}




